 name: pyaos-ams-2020
 channels:
   - conda-forge
 dependencies:
   - python>=3.6,<3.8
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - metpy
   - siphon
   - pandas
   - xarray
   - ipywidgets
   - ffmpeg
   - boto3
   - botocore
   - jupyterlab